import { Report } from "./report"

let DSC: string = "Hola buenas tardes quiero reportar una fuga en la calle...."

export const REPORTS: Report[] = [
    {
        id: "00000001",
        name: "José",
        l_name: "Vasconcelos",
        mail: "mail",
        street: "street",
        street_ref: "x",
        prof: "other",
        desc: "Hola buenas tardes quiero reportar una fuga en la calle....",
        time: "3:45",
      },
      {
        id: "00000002",
        name: "Enrique",
        l_name: "Ponce",
        mail: "mail",
        street: "street",
        street_ref: "x",
        prof: "other",
        desc: "Hola buenas tardes quiero reportar una fuga en la calle....",
        time: "15:45",
      },
      {
        id: "00000003",
        name: "Abel",
        l_name: "Romain",
        mail: "mail",
        street: "street",
        street_ref: "x",
        prof: "other",
        desc: "Hola buenas tardes quiero reportar una fuga en la calle....",
        time: "19:45",
      },
      {
        id: "00000003",
        name: "Abel",
        l_name: "Romain",
        mail: "mail",
        street: "street",
        street_ref: "x",
        prof: "other",
        desc: "Hola buenas tardes quiero reportar una fuga en la calle....",
        time: "19:45",
      },
      {
        id: "00000005",
        name: "Abel",
        l_name: "Romain",
        mail: "mail",
        street: "street",
        street_ref: "x",
        prof: "other",
        desc: "Hola buenas tardes quiero reportar una fuga en la calle....",
        time: "19:45",
      },
  ];